### ISSUE TITLE
[BUG] default permissions wrong and umask variable not working

### ISSUE THREAD

**Issue by Tumtum2814** [linuxserver/docker-deluge#189] opened 2023-08-22 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

files being written with 744, set umask to 022 with no behavior change

### Expected Behavior

was expecting 755 for files

### Steps To Reproduce

running latest  linuxserver/deluge
download file,
check permissions , only owner can write.

### Environment

```markdown
- OS: unraid
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.4"
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    #network_mode: host # run on the vpn network
    networks:
      - npm-network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK=${UMASK}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DOWN}:/downloads # downloads folder
      - ${DATA}/config/deluge:/config # config files
```

### Container logs

```bash
Connection to 127.0.0.1 58846 port [tcp/*] succeeded!
Connection to 127.0.0.1 8112 port [tcp/*] succeeded!
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment] 2023-08-22 19:54
mask 022 equals 644 for files, aka rw-r--r--
https://www.linuxtrainingacademy.com/all-umasks/

**Comment by drizuid** [comment] 2023-10-11 13:19
closing this due to no reply from OP. a umask os 022 would set 755 for a directory and 644 for a file. The expected behavior in the thread should not ever happen.

**Closed by drizuid** 2023-10-11 13:19 UTC
Labels: no-issue-activity
