### ISSUE TITLE
Publish Deluge 2.1.1

### ISSUE THREAD

**Issue by ngosang** [linuxserver/docker-deluge#154] opened 2022-07-13 22:36 UTC
Latest release from LinuxServer is 2.0.5 but 2.1.1 is out.
Take a look at the changelog => https://deluge.readthedocs.io/en/latest/changelog.html

Breaking changes

    Python 2 support removed (Python >= 3.6)

    libtorrent minimum requirement increased (>= 1.2).

**Comment by Roxedus** [comment] 2022-07-13 22:38
Dupe of #153

**Closed by Roxedus** 2022-07-13 22:38 UTC
