### ISSUE TITLE
Unable to add label.

### ISSUE THREAD

**Issue by neuman1812** [linuxserver/docker-deluge#97] opened 2020-07-02 00:48 UTC
## Expected Behavior
When I manually add a torrent Im unable to add a label to magnets

## Current Behavior
Currently unable to manually add label,  The only option is " No label"

--Note:  I can create labels,  but I'm unable to add them to magnets.

## Steps to Reproduce
Add torrent or magnent link via url
Attempt to manually add label

## Environment
Ubuntu 20.04
**CPU architecture:** x86_64
docker installed via apt- Repository (https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

```
## Docker Compose
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - UMASK_SET=022
      - TZ=America/New_York # timezone, defined in .env
    volumes:
      - /data/Torrents/:/data/Torrents # downloads folder

```

## Docker logs
Docker logs  Can be found here: https://hastebin.com/unupibomen.sql

This includes the first startup and config via docker compose.  Second run is automated startup.

**Comment by j0nnymoe** [comment] 2020-07-02 07:18
Just tested with a magnet link and it's working fine here.
![image](https://user-images.githubusercontent.com/10374553/86328293-809c2d80-bc3c-11ea-9382-3ea1081ff2ab.png)
You seem to be missing a `/config` mount.

**Comment by JoshStark** [comment] 2020-07-02 07:24
This is a duplicate of #96.

**Comment by j0nnymoe** [comment] 2020-07-06 09:00
Closed due to no response.

**Closed by j0nnymoe** 2020-07-06 09:00 UTC
Labels: duplicate
