### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by hfunder** [linuxserver/docker-deluge#20] opened 2017-01-08 08:55 UTC
Installed on Synology 1815 DSM 6.02 with latest docer package

Have other of your containers configured and running and never an issue with permissions

When adding a torrent it downloads a few kilobytes but when it has to write it to the disk it says:
"Permission denied: /Downloads/Incomplete/...."

Have looked in forums for solution but no luck.

**Comment by sparklyballs** [comment] 2017-01-08 10:52
with no run command or gui information we cannot help you with your local permissions issue

**Comment by hfunder** [comment] 2017-01-08 11:16
there is no run command set by the user in synology docker
have attached the config of the container in synology docker and the gui of deluge folder config
![1](https://cloud.githubusercontent.com/assets/21113410/21749290/dcf49c02-d5d6-11e6-8f3e-1eb1985d4eca.jpg)
![2](https://cloud.githubusercontent.com/assets/21113410/21749292/e309112c-d5d6-11e6-9d51-d2c89e912ec7.jpg)
![3](https://cloud.githubusercontent.com/assets/21113410/21749294/e7c7d216-d5d6-11e6-8c3d-304b68875896.jpg)
![4](https://cloud.githubusercontent.com/assets/21113410/21749295/eb181642-d5d6-11e6-937b-18c19954dc69.jpg)

**Comment by sparklyballs** [comment] 2017-01-08 11:20
you haven't configured deluge side

/downloads is not the same as /Downloads

linux is case sensitive.

closing this.

**Closed by sparklyballs** 2017-01-08 11:20 UTC

**Comment by owzo** [comment] 2017-03-24 01:57
I am also having this same issue, may I have some assistance?

Currently running unraid v6 using linuxserver/deluge:latest.
I have confirmed that all spelling is correct in the file structure.
I have also confirmed that ll my download locations are chmod 777.

Please let me know what other information you may need and possibly where to find this information.

I am an experienced Linux user just new to unraid and docker

![deluge permission denied](https://cloud.githubusercontent.com/assets/26640005/24277452/86af37ea-1013-11e7-9b0f-4791daac148c.PNG)

Kind regards,
Owzo

**Comment by sparklyballs** [comment] 2017-03-24 08:04
you have configured it incorrectly in the deluge webui.

/downloads is what you need to set

**Comment by CHBMB** [comment] 2017-03-24 10:58
@owzo Post your docker run command.  Should be what @sparklyballs says, but only way to be really sure is to see how you've set it up in the first place.

**Comment by owzo** [comment] 2017-03-24 12:34
@sparklyballs 🥇 Thank you so very much I was working on this for hours trying different configurations, however this worked and I am now on my way to greatness because of you.

**Comment by jokerigno** [comment] 2017-03-28 19:03
Hi all, 

I have the same problem. 

Below you can find my configuration:

![image](https://cloud.githubusercontent.com/assets/23552762/24422444/de09604e-13f9-11e7-9d83-fafcaeb6342a.png)

![image](https://cloud.githubusercontent.com/assets/23552762/24422475/f387927e-13f9-11e7-90b0-e98772e03f5d.png)

![image](https://cloud.githubusercontent.com/assets/23552762/24422493/021ebdd0-13fa-11e7-9ef9-0944ae2d9997.png)

Any help appreciated!

**Comment by aptalca** [comment] 2017-03-28 19:14
Check the permissions on the /Download/Temp folder and compare to the PUID and GUID you used

**Comment by jokerigno** [comment] 2017-03-28 20:28
I reinstalled the cointainer using Putty (and adding PUID and GUID). It worked! 

Thank you!

**Comment by owzo** [comment] 2017-07-05 23:28
Im haveing the same issue again, i moved away from unraid for a bit and now im back, can any one help?

`root@unraid:/mnt/user/downloads/incomplete# ls -la /mnt/user/downloads/complete
total 0
drwxrwxr-x 1 nobody users   6 Jun 27 12:16 ./
drwxrwxr-x 1 nobody users 110 Jun 30 08:26 ../
`

![deluge config](https://user-images.githubusercontent.com/26640005/27888768-08c1d2e4-61b6-11e7-9068-8970da43fa14.PNG)
![deluge docker config](https://user-images.githubusercontent.com/26640005/27888769-08c25e1c-61b6-11e7-80d0-3f5a41b20d41.PNG)

Sorry for coming back with this.

**Comment by sparklyballs** [comment] 2017-07-06 00:16
you're confusing external (unraid) side of the mount point with the internal (container) side

deluge needs to be set to use /downloads

**Comment by thenetbug** [comment] 2017-08-08 00:58
I'm not a very educated Linux user and all of a sudden I'm getting a "Permission Denied" error for any files in Deluge.

Would someone be able to point me in the right direction for where to troubleshoot this?

![unraid1](https://user-images.githubusercontent.com/30815881/29051793-31796f82-7bb3-11e7-8df6-e125a62f620a.png)
![unraid2](https://user-images.githubusercontent.com/30815881/29051792-3175fbd6-7bb3-11e7-9347-d36c265d0fe2.png)
Thanks.

**Comment by j0nnymoe** [comment] 2017-08-08 06:55
@thenetbug this is not our container, please seek help from the correct repo/support thread on the unraid forum.

**Comment by TempoChocolate** [comment] 2019-09-17 06:43
The creator of this docker container should change the default download location to /downloads from /root/Downloads. By default, anyone using this docker container will get permission issues.

**Comment by sparklyballs** [comment] 2019-09-17 07:51
> The creator of this docker container should change the default download location to /downloads from /root/Downloads. By default, anyone using this docker container will get permission issues.

or could just read the instructions 

https://github.com/linuxserver/docker-deluge#application-setup

**Comment by wjlafrance** [comment] 2021-06-29 01:17
> > The creator of this docker container should change the default download location to /downloads from /root/Downloads. By default, anyone using this docker container will get permission issues.
> 
> or could just read the instructions
> 
> https://github.com/linuxserver/docker-deluge#application-setup

It's two years later and I'm here with this same issue. Just a bit of feedback as a new user, I think the whole point of using your container is that it'll be internally consistent at least with it's own documentation. Please consider this a bug, and either update your documentation to suggest mounting the external data path as `/root/Downloads` or change the default deluge path to `/downloads`. Or at the very least use some backticks on the line you're pointing to so someone can see at a glance that a path is involved, if your container doesn't work out of the box.
